services:
  keycloak:
    image: mykeycloak:latest
    command: start --optimized
    environment:
      TAILCLOAKIFY_SHOW_SOCIAL_PROVIDERS_ON_REGISTER: "TRUE"
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/34.171.206.226.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/34.171.206.226-key.pem
    ports:
      - 8443:8443
      - 9000:9000
    restart: unless-stopped
    networks:
      - keycloak_network

  keycloak-exporter:
    image: mykeycloak:latest
    command: export --users same_file --dir /opt/keycloak/data/export
    volumes:
      - ./data:/opt/keycloak/data/export
      - ./certs:/opt/keycloak/conf/certs
    environment:
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak_network
    profiles:
      - export

networks:
  keycloak_network:
    driver: bridge