services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - 5432:5432  # DISABLED - PostgreSQL hanya accessible dari Docker network
    networks:
      - keycloak_network

  keycloak:

    image: mykeycloak:latest
    command: start --optimized

    environment:
      TAILCLOAKIFY_SHOW_SOCIAL_PROVIDERS_ON_REGISTER: "TRUE"
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/34.171.206.226.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/34.171.206.226-key.pem
    ports:
      - 8443:8443
      - 9000:9000
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - keycloak_network

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge